### ISSUE TITLE
Add flag to allow for sending messages without running `init`

### ISSUE THREAD

**Issue by ZeinHajjAli** [ZeinHajjAli/slacknotifpy#2]
`slacknotif run -i <script.py> [job_name] token=[API_TOKEN] channel=[CHANNEL_ID] success_message=[MSG] failure_message=[MSG]`

`slacknotif run -ic "<BASH_COMMANDS>" [job_name] token=[API_TOKEN] channel=[CHANNEL_ID] success_message=[MSG] failure_message=[MSG]`

Should bypass the check for config file and load directly from the args

Can probably be done just by editing the parser setup

**Comment by bjo5029** [comment]
Hi, I've created a pull request (#3) that implements the requested feature. The PR adds support for sending Slack messages without requiring the init command by introducing --token and --channel arguments to the run command. These arguments allow users to bypass the configuration file and directly provide the necessary credentials via the command line.

Please feel free to review and let me know if there are any changes or improvements you'd like to see!

**Comment by ZeinHajjAli** [comment]
Thanks! Had to make some edits to get it working, but merged!
